// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkzmyusntmpqlvzkvgll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inprem15dXNudG1wcWx2emt2Z2xsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNTYyNDUsImV4cCI6MjA3MDkzMjI0NX0.taAHSO4lzqWjsr7Nax3ojel29696VMeZwLzMQ1tfbOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});